import type { Config } from "tailwindcss";

/** Papel & Grafite: os componentes consomem apenas tokens semânticos. */
const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./lib/**/*.{ts,tsx}"],
  theme: {
    fontSize: {
      "2xs": ["11px", "16px"],
      xs: ["12px", "18px"],
      sm: ["13px", "20px"],
      base: ["14px", "22px"],
      md: ["16px", "24px"],
      lg: ["20px", "28px"],
      xl: ["26px", "32px"],
      "2xl": ["34px", "40px"],
    },
    extend: {
      colors: {
        fundo: "rgb(var(--fundo-rgb) / <alpha-value>)",
        "fundo-afundado": "rgb(var(--fundo-afundado-rgb) / <alpha-value>)",
        superficie: "rgb(var(--superficie-rgb) / <alpha-value>)",
        "superficie-alta": "rgb(var(--superficie-alta-rgb) / <alpha-value>)",
        "tinta-forte": "rgb(var(--tinta-forte-rgb) / <alpha-value>)",
        tinta: "rgb(var(--tinta-rgb) / <alpha-value>)",
        "tinta-suave": "rgb(var(--tinta-suave-rgb) / <alpha-value>)",
        "tinta-fraca": "rgb(var(--tinta-fraca-rgb) / <alpha-value>)",
        traco: "rgb(var(--traco-rgb) / <alpha-value>)",
        "traco-forte": "rgb(var(--traco-forte-rgb) / <alpha-value>)",
        acento: "rgb(var(--acento-rgb) / <alpha-value>)",
        "acento-escuro": "rgb(var(--acento-escuro-rgb) / <alpha-value>)",
        "acento-tenue": "rgb(var(--acento-tenue-rgb) / <alpha-value>)",
        "acento-borda": "rgb(var(--acento-borda-rgb) / <alpha-value>)",
        ok: "rgb(var(--ok-rgb) / <alpha-value>)",
        "ok-tenue": "rgb(var(--ok-tenue-rgb) / <alpha-value>)",
        espera: "rgb(var(--espera-rgb) / <alpha-value>)",
        "espera-tenue": "rgb(var(--espera-tenue-rgb) / <alpha-value>)",
        erro: "rgb(var(--erro-rgb) / <alpha-value>)",
        "erro-tenue": "rgb(var(--erro-tenue-rgb) / <alpha-value>)",
        info: "rgb(var(--info-rgb) / <alpha-value>)",
        "info-tenue": "rgb(var(--info-tenue-rgb) / <alpha-value>)",
        neutro: "rgb(var(--neutro-rgb) / <alpha-value>)",
        "neutro-tenue": "rgb(var(--neutro-tenue-rgb) / <alpha-value>)",
        /* aliases temporários preservam as telas enquanto os nomes migram. */
        bg: "rgb(var(--fundo-rgb) / <alpha-value>)",
        "bg-deep": "rgb(var(--fundo-afundado-rgb) / <alpha-value>)",
        surface: "rgb(var(--superficie-rgb) / <alpha-value>)",
        "surface-2": "rgb(var(--fundo-afundado-rgb) / <alpha-value>)",
        ink: "rgb(var(--tinta-forte-rgb) / <alpha-value>)",
        "ink-muted": "rgb(var(--tinta-suave-rgb) / <alpha-value>)",
        "ink-2": "rgb(var(--tinta-rgb) / <alpha-value>)",
        "ink-faint": "rgb(var(--tinta-fraca-rgb) / <alpha-value>)",
        accent: "rgb(var(--acento-rgb) / <alpha-value>)",
        "accent-deep": "rgb(var(--acento-escuro-rgb) / <alpha-value>)",
        "accent-bright": "rgb(var(--acento-rgb) / <alpha-value>)",
        "accent-soft": "rgb(var(--acento-tenue-rgb) / <alpha-value>)",
        "accent-glow": "rgb(var(--acento-borda-rgb) / <alpha-value>)",
        line: "rgb(var(--traco-rgb) / <alpha-value>)",
        "line-strong": "rgb(var(--traco-forte-rgb) / <alpha-value>)",
        warn: "rgb(var(--espera-rgb) / <alpha-value>)",
        "warn-soft": "rgb(var(--espera-tenue-rgb) / <alpha-value>)",
        danger: "rgb(var(--erro-rgb) / <alpha-value>)",
        "danger-soft": "rgb(var(--erro-tenue-rgb) / <alpha-value>)",
        "info-soft": "rgb(var(--info-tenue-rgb) / <alpha-value>)",
        sidebar: "rgb(var(--sidebar-rgb) / <alpha-value>)",
        "sidebar-2": "rgb(var(--sidebar-alta-rgb) / <alpha-value>)",
        "sidebar-hover": "rgb(var(--sidebar-hover-rgb) / <alpha-value>)",
        "sidebar-line": "rgb(var(--sidebar-traco-rgb) / <alpha-value>)",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "Inter", "system-ui", "sans-serif"],
        display: ["var(--font-sans)", "Inter", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "JetBrains Mono", "ui-monospace", "monospace"],
        serif: ["Georgia", "serif"],
      },
      borderRadius: { sm: "4px", DEFAULT: "6px", md: "6px", lg: "8px", xl: "12px", card: "8px", "card-lg": "12px", pill: "999px" },
      boxShadow: { card: "none", "card-hover": "none", pop: "var(--sombra-2)", nivel1: "var(--sombra-1)", nivel2: "var(--sombra-2)" },
      transitionDuration: { 120: "120ms", 180: "180ms", 240: "240ms" },
      transitionTimingFunction: { produto: "cubic-bezier(.2, 0, 0, 1)" },
      keyframes: {
        pulso: { "0%, 100%": { opacity: "1" }, "50%": { opacity: ".42" } },
        shimmer: { "0%": { opacity: ".45" }, "50%": { opacity: ".8" }, "100%": { opacity: ".45" } },
        "fade-in": { from: { opacity: "0" }, to: { opacity: "1" } },
        "scale-in": { from: { opacity: "0", transform: "scale(.985)" }, to: { opacity: "1", transform: "scale(1)" } },
        "slide-in-right": { from: { opacity: "0", transform: "translateX(16px)" }, to: { opacity: "1", transform: "translateX(0)" } },
      },
      animation: {
        pulse: "pulso 2s cubic-bezier(.2,0,0,1) infinite",
        "fade-in": "fade-in 180ms cubic-bezier(.2,0,0,1) both",
        "scale-in": "scale-in 180ms cubic-bezier(.2,0,0,1) both",
        "slide-in-right": "slide-in-right 240ms cubic-bezier(.2,0,0,1) both",
      },
    },
  },
  plugins: [],
};
export default config;
