"use client";
import { useEffect, useId, useRef, type ReactNode } from "react";
import { cn } from "@/lib/cn";
export function Modal({ aberto, aoFechar, titulo, children, className }: { aberto: boolean; aoFechar: () => void; titulo: string; children: ReactNode; className?: string }) {
  const tituloId = useId(); const painel = useRef<HTMLDivElement>(null); const gatilho = useRef<HTMLElement | null>(null);
  useEffect(() => { if (!aberto) return; gatilho.current = document.activeElement as HTMLElement; const anterior = document.body.style.overflow; document.body.style.overflow = "hidden"; const elementos = () => Array.from(painel.current?.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href],[tabindex]:not([tabindex="-1"])') ?? []); elementos()[0]?.focus(); const tecla = (e: KeyboardEvent) => { if (e.key === "Escape") aoFechar(); if (e.key === "Tab") { const lista = elementos(); if (!lista.length) return; const primeiro = lista[0]; const ultimo = lista[lista.length - 1]; if (e.shiftKey && document.activeElement === primeiro) { e.preventDefault(); ultimo.focus(); } else if (!e.shiftKey && document.activeElement === ultimo) { e.preventDefault(); primeiro.focus(); } } }; document.addEventListener("keydown", tecla); return () => { document.removeEventListener("keydown", tecla); document.body.style.overflow = anterior; gatilho.current?.focus(); }; }, [aberto, aoFechar]);
  if (!aberto) return null;
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4" role="presentation"><button className="absolute inset-0 h-full w-full bg-tinta-forte/55" aria-label="Fechar diálogo" onClick={aoFechar} /><div ref={painel} role="dialog" aria-modal="true" aria-labelledby={tituloId} className={cn("relative z-10 max-h-[90vh] w-full max-w-[560px] overflow-y-auto rounded-xl border border-traco bg-superficie-alta p-5 shadow-nivel2", className)}><h2 id={tituloId} className="text-md font-semibold">{titulo}</h2>{children}</div></div>;
}
