"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { usePapel } from "@/lib/papel";
import { Icone } from "./icons";
const grupos = [
  { titulo: "Visão geral", itens: [["/dashboard", "Painel", "dashboard"], ["/dashboard/atencao", "Atenção", "alerta"], ["/dashboard/execucoes", "Execuções", "atividade"]] },
  { titulo: "Fiscal", itens: [["/dashboard/documentos", "Documentos", "documento"], ["/dashboard/importacoes", "Importações", "importacao"], ["/dashboard/empresas", "Empresas", "empresa"], ["/dashboard/certificados", "Certificados", "escudo"], ["/dashboard/relatorios", "Fechamento", "grafico"]] },
  { titulo: "Sistema", itens: [["/dashboard/saude", "Saúde", "hd"], ["/dashboard/configuracoes", "Configurações", "engrenagem"], ["/dashboard/auditoria", "Auditoria", "olho"], ["/dashboard/usuarios", "Equipe", "usuarios"]] },
] as const;
export function Sidebar({ aberto, aoFechar }: { aberto: boolean; aoFechar: () => void }) {
  const rota = usePathname(); const { papel } = usePapel(); const [contagem, setContagem] = useState({ total: 0, criticos: 0 }); const [recolhida, setRecolhida] = useState(false);
  useEffect(() => { const salva = localStorage.getItem("notasflow:sidebar-recolhida") === "1"; setRecolhida(salva); let vivo = true; const carregar = () => { if (document.hidden) return; api.contagemAlertas().then((v) => { if (vivo) setContagem(v); }).catch(() => undefined); }; carregar(); const intervalo = window.setInterval(carregar, 60_000); document.addEventListener("visibilitychange", carregar); return () => { vivo = false; window.clearInterval(intervalo); document.removeEventListener("visibilitychange", carregar); }; }, []);
  return <><button type="button" onClick={aoFechar} aria-label="Fechar menu" className={`nao-imprimir fixed inset-0 z-30 bg-tinta-forte/50 transition-opacity lg:hidden ${aberto ? "opacity-100" : "pointer-events-none opacity-0"}`} /><aside className={`nao-imprimir fixed inset-y-0 left-0 z-40 flex flex-col border-r border-sidebar-line bg-sidebar transition-[width,transform] duration-240 ease-produto lg:sticky lg:top-0 lg:h-screen lg:translate-x-0 ${recolhida ? "w-14" : "w-60"} ${aberto ? "translate-x-0" : "-translate-x-full"}`}>
    <Link href="/dashboard" onClick={aoFechar} className="flex h-14 items-center gap-3 border-b border-sidebar-line px-3 text-white"><span className="flex h-8 w-8 flex-none items-center justify-center rounded-md border border-white/20 font-semibold">N</span>{!recolhida && <span className="font-semibold">NotasFlow</span>}</Link>
    <nav className="flex-1 overflow-y-auto px-2 py-4" aria-label="Navegação principal">{grupos.map((grupo) => <div className="mb-5" key={grupo.titulo}>{!recolhida && <p className="mb-1 px-2 text-2xs font-medium uppercase tracking-[.04em] text-white/45">{grupo.titulo}</p>}{grupo.itens.filter(([href]) => href !== "/dashboard/usuarios" || papel === "admin").filter(([href]) => href !== "/dashboard/auditoria" || papel !== "leitura").map(([href, rotulo, icone]) => { const ativo = href === "/dashboard" ? rota === href : rota.startsWith(href); const atencao = href === "/dashboard/atencao"; return <Link key={href} href={href} onClick={aoFechar} title={recolhida ? rotulo : undefined} className={`nav-item ${ativo ? "nav-item-ativo" : ""}`}><Icone nome={icone} className="h-[18px] w-[18px] flex-none" />{!recolhida && <><span className="flex-1">{rotulo}</span>{atencao && contagem.total > 0 && <span className={`min-w-6 rounded-sm px-1 text-center font-mono text-xs ${contagem.criticos ? "bg-erro text-white" : "bg-espera text-white"}`}>{contagem.total > 99 ? "99+" : contagem.total}</span>}</>}</Link>; })}</div>)}</nav>
    <button type="button" className="m-2 flex h-10 items-center justify-center rounded-md text-white/70 hover:bg-white/5 hover:text-white" onClick={() => { const valor = !recolhida; setRecolhida(valor); localStorage.setItem("notasflow:sidebar-recolhida", valor ? "1" : "0"); }} aria-label={recolhida ? "Expandir menu" : "Recolher menu"}><span aria-hidden="true">{recolhida ? "›" : "‹"}</span>{!recolhida && <span className="ml-2 text-xs">Recolher menu</span>}</button>
  </aside></>;
}
